### ISSUE TITLE
关于给指定成员分配指定老婆的方式

### ISSUE THREAD

**Issue by Akineru** [SonderXiaoming/dailywife#2]
本人不太会python，想尝试按照超级用户的方式，将条件和结果的wife_id改成对应QQ号，发现并不能生效。请问具体应该怎么操作呢

**Comment by frathy** [comment]
删掉/注释82行if priv.check_priv(ev, priv.SUPERUSER):
和83行wife_id = bot_id。替换为
    if str(user_id) == '这里填选老婆玩家的qq号1'
        wife_id = '这里填固定老婆的qq号2'
这样qq1发送今日老婆就固定为qq2了。
后面再指定可以用elif嵌套。

**Comment by SonderXiaoming** [comment]
记得别忘了id_list.remove(int('这里填固定老婆的qq号2'))，防止被别人抽到

**Comment by Akineru** [comment]
好的好的，十分感谢
